config/routes.rb
Rails.application.routes.draw do

	resources :subjects

	root 'home#index'
	get 'home/index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/subject.rb
class Subject < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  	@subjects = Subject.all.sort{|a,b| b.updated_at <=> a.updated_at}
  end
end

app/controllers/subjects_controller.rb
class SubjectsController < ApplicationController

	def index
		@subjects = Subject.all
	end

	def show

		@subject = Subject.find(params[:id])

	end

	def new

		@subject = Subject.new 
		
	end

	def create

		Subject.create(subject_params)

		redirect_to root_path

	end

	private

	def subject_params

		params.require(:subject).permit(:name,:description,:start,:end)
		
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/classes_helper.rb
module ClassesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_navbar.html.erb
<nav class="navbar navbar-dark bg-light">
  <a class="navbar-brand text-dark" href="/home/index" >Rentete</a>
  <form class="form-inline">
   <a href="<%= new_subject_path %>" class="btn btn-primary">Add Class</a>
  </form>
</nav>

app/views/home/index.html.erb
<div class="card-deck">

	<% @subjects.each do |subject| %>
	

	<div class="card m-3" style="width: 18rem;">
		<img src="/assets/kuala-lumpur.jpg" class="card-img-top" alt="astana">
		<div class="card-body">
			<h5 class="card-text"><%= subject.name %></h5>
			<p class="card-text"><%= subject.description %></p>
			<p class="card-text"><small class="text-muted"><%= time_ago_in_words subject.created_at %> ago</small></p>
			<a href="<%= subject_path(subject.id) %>" class="btn btn-dark">More Info</a>
			<button type="submit" class="btn btn-dark">Check Class</button>
		</div>
	</div>

	<% end %>

</div>

<style type="text/css">

@media (min-width:768px) {
	.card-deck > .card
	{
		width: 29%;
		flex-wrap: wrap;
		flex: initial; 
	}
}

</style>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rentete</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'home/navbar' %>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/subjects/index.html.erb
<div class="card" style="width: 18rem;">
  <img src="/assets/kuala-lumpur.jpg" class="card-img-top" alt="astana">
  <div class="card-body">
    <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
  	<a href= classe_path(@class) class="btn btn-primary">More Info</a>
  	<a href="" class="btn btn-primary">Invite</a>
  </div>
</div>

app/views/subjects/new.html.erb
<%= form_for @subject, url: subjects_path, html: { class: 'needs-validation'} do %>

<div class="form-row">

  <div class="col-md-4 mb-3">
    <label for="validationCustom01">Class Name</label>
    <input type="text" name="subject[name]" class="form-control" id="validationCustom01" placeholder="e.g Web Dev Class"required>
    <div class="valid-feedback">
      Looks good!
    </div>
  </div>

  <div class="col-md-5 mb-3">
    <label for="validationCustom03">City</label>
    <input type="text" name="subject[city]" class="form-control" id="validationCustom03" placeholder="e.g New York" required>
    <div class="invalid-feedback">
      Please provide a valid city.
    </div>
  </div>

  <div class="col-md-6 mb-6">
    <label for="validationCustom02">Class Description</label>
    <input type="text" name="subject[description]" class="form-control" id="validationCustom02" placeholder="What are you going to learn" required>
    <div class="valid-feedback">
      Looks good!
    </div>
  </div>

</div>

<button class="btn btn-primary" type="submit">Submit form</button>

<% end %>

<script>
// Example starter JavaScript for disabling form submissions if there are invalid fields
(function() {
  'use strict';
  window.addEventListener('load', function() {
    // Fetch all the forms we want to apply custom Bootstrap validation styles to
    var forms = document.getElementsByClassName('needs-validation');
    // Loop over them and prevent submission
    var validation = Array.prototype.filter.call(forms, function(form) {
      form.addEventListener('submit', function(event) {
        if (form.checkValidity() === false) {
          event.preventDefault();
          event.stopPropagation();
        }
        form.classList.add('was-validated');
      }, false);
    });
  }, false);
})();
</script>

app/views/subjects/show.html.erb
<div class="card bg-dark text-white">
  <img src="/assets/kuala-lumpur.jpg" height="800" class="card-img" alt="...">
  <div class="card-img-overlay">
    <h5 class="card-title"><%= @subject.name %></h5>
    <p class="card-text"><%= @subject.description %></p>
    <p class="card-text">Posted <%= time_ago_in_words @subject.created_at %> ago</p>
  </div>
</div>